name: CI

on: [push, pull_request]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y libnuma-dev tcl8.6 tclx
    - name: make
      # Fail build if there are warnings. Linux always builds with
      # -DHAVE_NUMA -lnuma and MALLOC=libc forced (src/Makefile:133-140).
      run: |
        cd src
        make -j$(nproc) REDIS_CFLAGS='-Werror'
    - name: test
      run: ./runtest --verbose --tags -slow --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose --dump-logs
    - name: validate commands.def up to date
      run: |
        touch src/commands/ping.json
        make commands.def
        dirty=$(git diff)
        if [[ ! -z  $dirty ]]; then echo $dirty; exit 1; fi

  sanitizer-address:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y libnuma-dev tcl8.6 tclx
      - name: make
        run: |
          cd src
          make -j$(nproc) SANITIZER=address REDIS_CFLAGS='-Werror'
      - name: test
        run: ./runtest --verbose --tags -slow --dump-logs

  numaflow:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: build + test
      run: |
        cd numaflow
        make
        make test
